services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data:
